version: "3.8"

services:
  postgres:
    image: postgres
    container_name: ai-agent-psql
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ~/ai/db/ai-agent-bot:/var/lib/postgresql/data

  analyzer:
    image: mcr.microsoft.com/presidio-analyzer:latest
    container_name: analyzer
    ports:
      - "5002:3000"
    platform: linux/amd64
